# Generated by Django 5.1.2 on 2024-10-25 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counselor',
            old_name='manager_id',
            new_name='manager',
        ),
    ]
