# Generated by Django 5.1.2 on 2024-10-25 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor_app', '0002_rename_manager_id_counselor_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnrollStudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('qualification', models.CharField(choices=[('inter', 'Intermediate'), ('diploma', 'Diploma'), ('degree', 'Degree'), ('btech', 'Bachelor Technology'), ('mtech', 'Master Technology')], max_length=150)),
                ('course_name', models.CharField(choices=[('python_full_stack', 'Python Full Stack'), ('java_full_stack', 'Java Full Stack'), ('data_science', 'Data Science'), ('aws', 'AWS Cloud'), ('devops', 'Dev Ops'), ('digital_marketing', 'Digital Marketing'), ('ui_ux', 'UI / UX')], max_length=50)),
                ('education_status', models.CharField(choices=[('passed_out', 'Passed Out'), ('pursuing', 'Pursuing')], max_length=20)),
                ('branch', models.CharField(max_length=150)),
                ('course_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselor_app.counselor')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselor_app.manager')),
            ],
        ),
    ]
