# Generated by Django 5.1.2 on 2024-10-28 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor_app', '0003_enrollstudents'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('employee_id', models.CharField(max_length=15, unique=True)),
                ('role_type', models.CharField(max_length=50)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselor_app.manager')),
            ],
        ),
        migrations.DeleteModel(
            name='EnrollStudents',
        ),
    ]
