# Generated by Django 5.1.2 on 2024-11-04 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor_app', '0007_studentenrollment_delete_enrollstudentsdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollment',
            name='payment_status',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
