# Generated by Django 5.1.2 on 2024-11-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor_app', '0011_studentpaymentdetails_delete_paymentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentpaymentdetails',
            name='registration_fee',
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='registration_fee_status',
            field=models.CharField(default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='registration_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
