# Generated by Django 5.1.2 on 2024-11-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counselor_app', '0013_registrationpaymentdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentenrollment',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='registration_fee_status',
        ),
    ]
